### ISSUE TITLE
SMS hook issue

### ISSUE THREAD

**Issue by akashjarad** [rams3sh/cowin4all#13]
getting below error on sms otp read with sms sync app, works fine when publish is initiated manually (clicking publish button )
`WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
2021-05-30 23:19:47,323 — [Module Name: uvicorn.error] — [PID: 21494] — [Thread : Thread-1] —  WARNING — [Method and Line  No: handle_events:175] — Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
2021-05-30 23:19:47,352 — [Module Name: uvicorn.error] — [PID: 21494] — [Thread : Thread-1] —  WARNING — [Method and Line  No: handle_events:175] — Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/demo/Documents/project/cowinnotify/cowin4all-b9dc3f4fd0331682a019744d95725ecf72282013/env/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line`

**Comment by rams3sh** [comment]
Hey @akashjarad , can you please recheck the README and the code.

I have been working on some optmizations during last week and have made the complete setup pip compatible.

The README is completely revamped now. 

I think you should be able to get this run with help of new documentation.

Let me know if any help is required. 


Keeping this issue open until then. Confirm once you are able to set it up so that I can close it.

Cheers and Be safe :)

**Comment by akashjarad** [comment]
@rams3sh  facing same issue ,no the issue is also occurring  when i publish otp manually also from sync sms app
i tried it in test mode also but same issue

**Comment by akashjarad** [comment]
@rams3sh  i checked the issue again it was due to adding https  in the smssync app , replacing with http works , you can close the issue.
